### ISSUE TITLE
Does the macOS Powerchime work for you

### ISSUE THREAD

**Issue by Human7900** [ulidu/HP-Probook-450-G6-Big-Sur-EFI#1]
Does the macOS Powerchime (the sound when you plug in the charger) work for you?

**Comment by ulidu** [comment]
Yes. It works. 👍

**Comment by ulidu** [comment]
> Does the macOS Powerchime (the sound when you plug in the charger) work for you?

Yes. It works. 👍

**Comment by Human7900** [comment]
It doesn't work for me. Can only be heard using headphones. Do you know any fix?
